### ISSUE TITLE
[Umbrella Issue] problems surfaced with TCE built atop tanzu-framework

### ISSUE THREAD

**Issue by joshrosso** [vmware-tanzu/community-edition#1035]
## Bug Report

This issue tracks the blockers we are hitting trying to get TCE to run atop [vmware-tanzu/tanzu-framework](https://github.com/vmware-tanzu/tanzu-framework).

* [x] [CAPD clusters utilize an alpine-based image for HA Proxy](https://github.com/vmware-tanzu/tanzu-framework/issues/210)
* [x] [Failed to bootstrap Azure clusters: Azure NMI image pointed to non-existent registry.](https://github.com/vmware-tanzu/tanzu-framework/issues/209)
* [x] [unable to run (kind) bootstrap cluster: cert-manager fails to provision webhook certs](https://github.com/vmware-tanzu/tanzu-framework/issues/206)
* [x] [cgroup mount point does not exist when running our kind image (e.g. bootstrap) on certain linux machines](https://github.com/vmware-tanzu/tanzu-framework/issues/118)
  * [x] note, we've decided to push this back to after dakar, so marking this as completed.
* [x] [Unable to create management cluster on AWS](https://github.com/vmware-tanzu/tanzu-framework/issues/116)
* [x] [make set-unstable-versions fails with errors](https://github.com/vmware-tanzu/tanzu-framework/issues/144)
    * note: workaround available; issue being investigated
* [x] [`tanzu management-cluster create --ui` appears to hang due to poor ux](https://github.com/vmware-tanzu/tanzu-framework/issues/254)
    * https://github.com/vmware-tanzu/tanzu-framework/pull/274
