### ISSUE TITLE
Verify management cluster e2e on vSphere is working correctly

### ISSUE THREAD

**Issue by dvonthenen** [vmware-tanzu/community-edition#3680]
## Verify e2e for management-clusters on vSphere

This issue tracks work for vSphere E2E tests for management clusters.

### Verification

- [ ] Execute/run e2e tests for management clusters. This should exercise:
  - [ ] create cluster
  - [ ] simple inspection of the cluster to make sure it's running
  - [ ] delete cluster
  - [ ] simple inspection to make sure the cluster is deleted
- [ ] Is this workflow being triggered by the daily build?
- [ ] Is this workflow being triggered by modifications to Makefile (for a Tanzu Framework version bump)?

### Issues found as a result of the audit?

We should prioritize these and determine if they are absolutely required for the workflow to function correctly and be reproducible.

-[ ] [vSphere management and workload cluster E2E test pipelines failures](https://github.com/vmware-tanzu/community-edition/issues/3132)
- [ ] [vSphere E2E test pipeline failures](https://github.com/vmware-tanzu/community-edition/issues/2898)
- [ ] [vSphere Self Hosted Runner connectivity issue](https://github.com/vmware-tanzu/community-edition/issues/2707)
- [ ] [Fix vSphere management + workload cluster E2E test failure](https://github.com/vmware-tanzu/community-edition/issues/2545)
