### ISSUE TITLE
Add Velero Package to TCE

### ISSUE THREAD

**Issue by joshrosso** [vmware-tanzu/community-edition#825]
## Supported providers
- Kind
- AWS
- vSphere

Todos:
- [x] [Push Velero images v1.6.1 to Harbor · Issue #999 · vmware-tanzu/tce](https://github.com/vmware-tanzu/tce/issues/999)
- [ ] [Update Velero's documentation to add instructions to run Minio as a Docker container (for evaluation) · Issue #3936 · vmware-tanzu/velero](https://github.com/vmware-tanzu/velero/issues/3936)
- [ ] [Update Velero's documentation to remove instructions to run Minio as a deployment (due to licensing issues) · Issue #3935 · vmware-tanzu/velero](https://github.com/vmware-tanzu/velero/issues/3935)
- [ ] Remove current setup do deploy Minio alongside Velero
- [ ] Investigate issue reported in https://github.com/vmware-tanzu/tce/issues/925#issuecomment-873026870

Pending decisions (c/c @dsu-igeek @eleanor-millman @reasonerjt):
- [x] Who will own this package, TCE or the Velero team
- [x] Where will this package live by (TCE) launch time, in the TCE repo, in the Velero repo, in another repo
